### ISSUE TITLE
[FEATURE REQUEST] save backups on local storage on given path

### ISSUE THREAD

**Issue by sinawic** [eduardolat/pgbackweb#19] opened 2024-08-04 14:20 UTC
hi
i wasn't able to use it bec of the destination settings
why should there only be `s3 object storage` as the destination.
i have mounted a volume to `/backups` inside the container
and i want to be able to store the backups in there instead of sending to a s3 storage

thanks in advance!

**Comment by eduardolat** [comment] 2024-08-04 22:51
Duplicate of #1 

A new version will be released today that includes exactly this feature in the same way you describe so there you have it :)

**Closed by eduardolat** 2024-08-04 22:51 UTC

**Comment by sinawic** [comment] 2024-08-06 07:19
hey
I can confirm that the feature is added
and is working as expected!

thanks for all the effort <3

here's [my channel](https://www.youtube.com/channel/UC33nD8gkUUAJr36E9di1bDA) link tho
I would appreciate if u give a visit
and I'll let u know when I get the video done!

@eduardolat

**Comment by eduardolat** [comment] 2024-08-06 17:36
Great, I'll be keeping an eye out

**Comment by sinawic** [comment] 2024-08-24 07:52
hey @eduardolat 
here's the video url 
i hope you like it
https://www.youtube.com/watch?v=vf7SLrSO8sw

**Comment by sinawic** [comment] 2024-08-24 07:56
also if you liked it
I'd really appreciate if you put the link to the video somewhere in the readme or something
anyway thanks for the tool :+1:

**Comment by eduardolat** [comment] 2024-09-08 18:12
Hi @sinawic, I've seen your video and it's great! Thank you very much for making it.

I've put it in the readme as a guide, I really appreciate it.

Don't forget that we have a discord server where we can chat more comfortably.

**Comment by sinawic** [comment] 2024-09-11 17:01
thanks really
i really appreciate it
of course i'll try to join it
