### ISSUE TITLE
Optionally disable periodic health check

### ISSUE THREAD

**Issue by nnamua** [eduardolat/pgbackweb#71] opened 2024-12-27 11:15 UTC
I am using pgbackweb with a Vercel Postgres DB. After deploying pgbackweb, I noticed a significantly higher cost due to the calculated database compute time. My guess is, that the health check periodically wakes the database instance, which results in the database never going to sleep and causing high compute time numbers.

I would love a feature, where I can disable the health checks and keep only the scheduled backups. As a quick fix, I think I will just stop the container until it is time to do the backup. Thank you for developing and maintaining such a great project!

**Comment by eduardolat** [comment] 2024-12-27 15:55
Same with neon db, duplicate of #59

**Closed by eduardolat** 2024-12-27 15:55 UTC
